# INFO: If you want to run both docker compose
# add the -p flag on each to separate them completely
# Ex: docker-compose -p mongodb-server -f docker-compose-mongodb.yml up

version: '3.5'

services:
  mongodb:
    image: mongo:3.6.22
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: xhp
      ME_CONFIG_BASICAUTH_PASSWORD: xhp

volumes:
  mongodb-data:
    name: mongodb-data
# INFO: Add Health Checks in The future
